import { FlaskConical, Info } from "lucide-react";
import type { DataContext } from "@/lib/types";

/**
 * Provenance notices.
 *
 * The mock-data banner is deliberately loud and impossible to miss: synthetic
 * prices shown without a warning are the one failure mode of this app that could
 * cause real financial harm (PRD §44).
 */
export function MockDataBanner({ context }: { context: DataContext }) {
  if (!context.isMockData) return null;
  return (
    <div
      role="alert"
      className="flex items-start gap-3 rounded-[var(--radius-card)] border border-cls-conflicting/40 bg-cls-conflicting/10 px-4 py-3"
    >
      <FlaskConical
        className="mt-0.5 h-4 w-4 shrink-0 text-cls-conflicting"
        aria-hidden
      />
      <div className="text-sm">
        <p className="font-semibold text-cls-conflicting">
          Synthetic development data
        </p>
        <p className="mt-0.5 text-ink-muted">
          Every figure on this page is generated by the mock provider and does not
          reflect any real market. Set{" "}
          <code className="rounded bg-surface-muted px-1 py-0.5 text-xs">
            MARKET_DATA_PROVIDER=yahoo
          </code>{" "}
          to use live data.
        </p>
      </div>
    </div>
  );
}

/** Quiet footer line: where the numbers came from and how fresh they are. */
export function ProvenanceNote({
  context,
  className,
}: {
  context: DataContext;
  className?: string;
}) {
  // Redaction blanks the label. Rendering "Source: ." would be worse than
  // rendering nothing, and this keeps every call site unchanged.
  if (!context.providerLabel) return null;

  return (
    <p className={className}>
      <span className="inline-flex items-start gap-1.5 text-xs text-ink-muted">
        <Info className="mt-0.5 h-3 w-3 shrink-0" aria-hidden />
        <span>
          Source: {context.providerLabel}
          {context.fromDatabase ? " (served from stored history)" : " (computed live)"}.
          {context.holidayCoverage === "PARTIAL"
            ? " Forward trading dates are projected from a holiday list that excludes lunar-calendar festival closures, so a projected date may fall on an unlisted exchange holiday."
            : ""}
        </span>
      </span>
    </p>
  );
}
